name: remediation/Remediation-Keepalive

run-name: remediation/Remediation-Keepalive-${{ inputs.Region }}-${{ inputs.InstanceId }}-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      InstanceId:
        type: string
        description: Instance ID
        required: true

      Region:
        type: string
        description: Region
        required: true

jobs:
  setup-job-environment:
    runs-on: ubuntu-latest
    concurrency:
      group: keepalive-${{ inputs.InstanceId }}
      cancel-in-progress: false
    steps:
      - name: Set Up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.Region }}

      - name: Check EC2 instance state, if running then runs SOP
        id: ec2-state
        run: |
          state=$(aws ec2 describe-instances --instance-ids ${{ inputs.InstanceId }} --query 'Reservations[0].Instances[0].State.Name' --output text)
          if [ "$state" != "running" ]; then
            echo "Instance is not in running state. Current Instance status: $state"
          fi
          echo "STATE=$state" >> $GITHUB_OUTPUT

      - name: Fetch component from ec2 instance tag 'role'
        if: ${{ steps.ec2-state.outputs.STATE == 'running' }}
        id: ec2-instance-tag
        run: |
          component=$(aws ec2 describe-tags --instance-ids ${{ inputs.InstanceId }} --filters "Name=resource-id,Values=${{ inputs.Region }}" "Name=key,Values=role" --region ${{ inputs.Region }} --query "Tags[0].Value" --output text)
          if [ -z "$component" ] || [ "$component" == "None" ]; then
            echo "No tag key 'role' is found"
          else
            echo "Role tag value: $component"
          fi
          echo "COMPONENT=$component" >> $GITHUB_OUTPUT

    outputs:
      INSTANCE_STATE: ${{ steps.ec2-state.outputs.STATE }}
      COMPONENT: ${{ steps.ec2-instance-tag.outputs.COMPONENT }}

  check-health-of-instance-and-restart:
    if: ${{ needs.setup-job-environment.outputs.COMPONENT == 'eventstore' || needs.setup-job-environment.outputs.INSTANCE_STATE == 'running' }}
    runs-on: ubuntu-latest
    needs: setup-job-environment
    steps:
      - name: Set Up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.Region }}

      - name: Check CloudWatch metrics
        id: instance-status-check
        run: |
          INSTANCE_ID="${{ inputs.InstanceId }}"
          REGION="${{ inputs.Region }}"
          METRICS=(StatusCheckFailed_System StatusCheckFailed_Instance StatusCheckFailed StatusCheckFailed_AttachedEBS)
          unhealthy=0

          for METRIC in "${METRICS[@]}"; do
            VALUE=$(aws cloudwatch get-metric-statistics \
              --namespace AWS/EC2 --metric-name "$METRIC" \
              --dimensions Name=InstanceId,Value=$INSTANCE_ID \
              --start-time $(date -u -d '-5 minutes' +%Y-%m-%dT%H:%M:%SZ) \
              --end-time $(date -u +%Y-%m-%dT%H:%M:%SZ) \
              --period 60 --statistics Maximum \
              --region $REGION \
              --query 'Datapoints[0].Maximum' --output text)

            if [[ "$VALUE" != "None" && "$VALUE" != "0.0" ]]; then
              echo "⚠️ $METRIC failed: $VALUE"
              unhealthy=1
            else
              echo "✅ $METRIC passed: $VALUE"
            fi
          done

          echo "UNHEALTHY=$unhealthy" >> $GITHUB_OUTPUT

      - name: Stopping instance if unhealthy
        if: ${{ steps.instance-status-check.outputs.UNHEALTHY == '1' }}
        run: |
          echo "Instance is unhealthy. Stopping..."
          aws ec2 stop-instances --region ${{ inputs.Region }} --instance-ids ${{ inputs.InstanceId }}
          
          echo "Waiting for instance to stop..."
          attempts=0
          max_attempts=200
          delay=15
          
          while [ $attempts -lt $max_attempts ]; do
            state=$(aws ec2 describe-instances --region ${{ inputs.Region }} \
              --instance-ids ${{ inputs.InstanceId }} \
              --query "Reservations[0].Instances[0].State.Name" --output text)
          
            echo "Attempt $((attempts+1)): Instance state is '$state'"
          
            if [ "$state" = "stopped" ]; then
              echo "Instance successfully stopped."
              break
            fi
          
            if [ "$state" = "terminated" ]; then
              echo "Instance is terminated. Exiting..."
              exit 1
            fi
          
            attempts=$((attempts + 1))
            sleep $delay
          done
          
          if [ $attempts -ge $max_attempts ]; then
            echo "Instance did not stop within expected time. Exiting..."
            exit 1
          fi
          
      - name: Starting instance
        if: ${{ steps.instance-status-check.outputs.UNHEALTHY == '1' }}
        run: |
          echo "Instance is Stopped. Starting instance..."                
          aws ec2 start-instances --region ${{ inputs.Region }} --instance-ids ${{ inputs.InstanceId }}
          sleep 20

      - name: Get SSM Document Name
        id: get-ssm-doc
        run: |
          document_name="AWS-RunShellScript" 
          echo "Using SSM Document: $document_name"
          echo "DOC_NAME=$document_name" >> "$GITHUB_OUTPUT"

      - name: Run SSM Command to check ssm-agent health
        id: send-command
        run: |
          cmd_id=$(aws ssm send-command \
            --instance-ids "${{ inputs.InstanceId }}" \
            --region "${{ inputs.Region }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Running date command" \
            --parameters commands="date" \
            --query "Command.CommandId" \
            --output text)
          
          echo "SSM Command ID: $cmd_id"
          echo "SSM Run Command Link- https://${{ inputs.REGION }}.console.aws.amazon.com/systems-manager/run-command/$cmd_id?region=${{ inputs.REGION }}"
          echo "CMD_ID=$cmd_id" >> "$GITHUB_OUTPUT"

      - name: Wait and Get Run Command Status
        id: check_status
        run: |
          echo "Waiting 15 seconds before checking command status..."
          sleep 15

          OUTPUT=$(aws ssm get-command-invocation \
            --command-id ${{ steps.send-command.outputs.cmd_id }} \
            --instance-id ${{ inputs.InstanceId }} \
            --output json)
          
          STATUS=$(echo "$OUTPUT" | jq -r '.Status')
          STDOUT=$(echo "$OUTPUT" | jq -r '.StandardOutputContent')
          STDERR=$(echo "$OUTPUT" | jq -r '.StandardErrorContent')

          echo "SSM Command Status: $STATUS"
          echo "::group::SSM Command Output"
          echo "$STDOUT"
          echo "::endgroup::"
          
          echo "::group::SSM Command Errors (if any)"
          echo "$STDERR"
          echo "::endgroup::"

          echo "SSM Command Status: $STATUS"
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"

      - name: Stopping Instance If SSM stuck in pending state
        if: ${{ steps.check_status.outputs.status != 'Pending' }}
        run: |
          echo "SSM command did not succeed. Rebooting instance..."
          aws ec2 stop-instances --region ${{ inputs.Region }} --instance-ids ${{ inputs.InstanceId }}
          
          echo "Waiting for instance to stop..."
          attempts=0
          max_attempts=200
          delay=15
          
          while [ $attempts -lt $max_attempts ]; do
            state=$(aws ec2 describe-instances --region ${{ inputs.Region }} \
              --instance-ids ${{ inputs.InstanceId }} \
              --query "Reservations[0].Instances[0].State.Name" --output text)
          
            echo "Attempt $((attempts+1)): Instance state is '$state'"
          
            if [ "$state" = "stopped" ]; then
              echo "Instance successfully stopped."
              break
            fi
          
            if [ "$state" = "terminated" ]; then
              echo "Instance is terminated. Exiting..."
              exit 1
            fi
          
            attempts=$((attempts + 1))
            sleep $delay
          done
          
          if [ $attempts -ge $max_attempts ]; then
            echo "Instance did not stop within expected time. Exiting..."
            exit 1
          fi
          
      - name: Starting instance
        if: ${{ steps.check_status.outputs.status != 'Pending' }}
        run: |
          echo "Instance is Stopped. Starting instance..."                
          aws ec2 start-instances --region ${{ inputs.Region }} --instance-ids ${{ inputs.InstanceId }}
          sleep 20
