name: remediation/Remediation-Keepalive

run-name: remediation/Remediation-Keepalive-${{ inputs.Region }}-${{ inputs.InstanceId }}-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      InstanceId:
        type: string
        description: Instance ID
        required: true

      Region:
        type: string
        description: Region
        required: true

jobs:
  execute-keepalive-remediation:
    runs-on: ubuntu-latest
    concurrency:
      group: keepalive-${{ inputs.InstanceId }}
      cancel-in-progress: false
    steps:
      - name: Set Up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.Region }}

      - name: Check EC2 instance state, if running then runs SOP
        id: ec2-state
        run: |
          state=$(aws ec2 describe-instances --instance-ids ${{ inputs.InstanceId }} --query 'Reservations[0].Instances[0].State.Name' --output text)
          if [ "$state" != "running" ]; then
            echo "Instance is not in running state. Current Instance status: $state"
          else
            echo "Current Instance status: $state"
          fi
          echo "STATE=$state" >> $GITHUB_OUTPUT          

      - name: Check CloudWatch metrics
        if: ${{ steps.ec2-state.outputs.STATE == 'running' }}
        id: instance-status-check
        run: |
          INSTANCE_ID="${{ inputs.InstanceId }}"
          REGION="${{ inputs.Region }}"
          METRICS=(StatusCheckFailed_System StatusCheckFailed_Instance StatusCheckFailed StatusCheckFailed_AttachedEBS)
          unhealthy=0

          for METRIC in "${METRICS[@]}"; do
            VALUE=$(aws cloudwatch get-metric-statistics \
              --namespace AWS/EC2 --metric-name "$METRIC" \
              --dimensions Name=InstanceId,Value=$INSTANCE_ID \
              --start-time $(date -u -d '-5 minutes' +%Y-%m-%dT%H:%M:%SZ) \
              --end-time $(date -u +%Y-%m-%dT%H:%M:%SZ) \
              --period 60 --statistics Maximum \
              --region $REGION \
              --query 'Datapoints[0].Maximum' --output text)

            if [[ "$VALUE" != "None" && "$VALUE" != "0.0" ]]; then
              echo "⚠️ $METRIC failed: $VALUE"
              unhealthy=1
            else
              echo "✅ $METRIC passed: $VALUE"
            fi
          done

          echo "UNHEALTHY=$unhealthy" >> $GITHUB_OUTPUT

      - name: Stopping instance if unhealthy
        if: ${{ steps.instance-status-check.outputs.UNHEALTHY == '1' && steps.ec2-state.outputs.STATE == 'running' }}
        run: |
          echo "Instance is unhealthy. Stopping..."
          aws ec2 stop-instances --region ${{ inputs.Region }} --instance-ids ${{ inputs.InstanceId }}
          
          echo "Waiting for instance to stop..."
          attempts=0
          max_attempts=200
          delay=15
          
          while [ $attempts -lt $max_attempts ]; do
            state=$(aws ec2 describe-instances --region ${{ inputs.Region }} \
              --instance-ids ${{ inputs.InstanceId }} \
              --query "Reservations[0].Instances[0].State.Name" --output text)
          
            echo "Attempt $((attempts+1)): Instance state is '$state'"
          
            if [ "$state" = "stopped" ]; then
              echo "Instance successfully stopped."
              break
            fi
          
            if [ "$state" = "terminated" ]; then
              echo "Instance is terminated. Exiting..."
              exit 1
            fi
          
            attempts=$((attempts + 1))
            sleep $delay
          done
          
          if [ $attempts -ge $max_attempts ]; then
            echo "Instance did not stop within expected time. Exiting..."
            exit 1
          fi
          
      - name: Starting instance
        if: ${{ steps.instance-status-check.outputs.UNHEALTHY == '1' && steps.ec2-state.outputs.STATE == 'running' }}
        run: |
          echo "Instance is Stopped. Starting instance..."                
          aws ec2 start-instances --region ${{ inputs.Region }} --instance-ids ${{ inputs.InstanceId }}
          sleep 20

      - name: Get SSM Document Name
        if: ${{ steps.instance-status-check.outputs.UNHEALTHY != '1' && steps.ec2-state.outputs.STATE == 'running' }}
        id: get-ssm-doc
        run: |
          documents=$(aws ssm list-documents --region ${{ inputs.REGION }} --filters Key=Owner,Values=Self --query "DocumentIdentifiers[*].Name" --output json)
          document_name=$(echo "$documents" | jq -r '.[] | select(contains("SsmDocument-RemediationActionSsmDocument"))')  
          echo "Using SSM Document: $document_name"
          echo "DOC_NAME=$document_name" >> "$GITHUB_OUTPUT"

      - name: Run SSM Command to check ssm-agent health
        if: ${{ steps.instance-status-check.outputs.UNHEALTHY != '1' && steps.ec2-state.outputs.STATE == 'running' }}
        id: send-command
        run: |
          cmd_id=$(aws ssm send-command \
            --document-name "${{ steps.get-ssm-doc.outputs.DOC_NAME }}" \
            --instance-ids ${{ inputs.InstanceId }} \
            --region ${{ inputs.Region }} \
            --parameters AlertName="keepalive" \
            --query 'Command.CommandId' --output text)
          
          echo "SSM Command ID: $cmd_id"
          echo "SSM Run Command Link- https://${{ inputs.REGION }}.console.aws.amazon.com/systems-manager/run-command/$cmd_id?region=${{ inputs.REGION }}"
          echo "CMD_ID=$cmd_id" >> "$GITHUB_OUTPUT"

      - name: Wait and Get Run Command Status
        if: ${{ steps.instance-status-check.outputs.UNHEALTHY != '1' && steps.ec2-state.outputs.STATE == 'running' }}
        id: check_status
        run: |
          echo "Waiting 15 seconds before checking command status..."
          sleep 15

          OUTPUT=$(aws ssm get-command-invocation \
            --command-id ${{ steps.send-command.outputs.cmd_id }} \
            --instance-id ${{ inputs.InstanceId }} \
            --output json)
          
          STATUS=$(echo "$OUTPUT" | jq -r '.Status')
          STDOUT=$(echo "$OUTPUT" | jq -r '.StandardOutputContent')
          STDERR=$(echo "$OUTPUT" | jq -r '.StandardErrorContent')

          echo "SSM Command Status: $STATUS"
          echo "::group::SSM Command Output"
          echo "$STDOUT"
          echo "::endgroup::"
          
          echo "::group::SSM Command Errors (if any)"
          echo "$STDERR"
          echo "::endgroup::"

          echo "SSM Command Status: $STATUS"
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"

      - name: Stopping Instance If SSM stuck in pending state
        if: ${{ steps.check_status.outputs.status == 'Pending' && steps.instance-status-check.outputs.UNHEALTHY != '1' && steps.ec2-state.outputs.STATE == 'running' }}
        run: |
          echo "SSM command did not succeed. Rebooting instance..."
          aws ec2 stop-instances --region ${{ inputs.Region }} --instance-ids ${{ inputs.InstanceId }}
          
          echo "Waiting for instance to stop..."
          attempts=0
          max_attempts=200
          delay=15
          
          while [ $attempts -lt $max_attempts ]; do
            state=$(aws ec2 describe-instances --region ${{ inputs.Region }} \
              --instance-ids ${{ inputs.InstanceId }} \
              --query "Reservations[0].Instances[0].State.Name" --output text)
          
            echo "Attempt $((attempts+1)): Instance state is '$state'"
          
            if [ "$state" = "stopped" ]; then
              echo "Instance successfully stopped."
              break
            fi
          
            if [ "$state" = "terminated" ]; then
              echo "Instance is terminated. Exiting..."
              exit 1
            fi
          
            attempts=$((attempts + 1))
            sleep $delay
          done
          
          if [ $attempts -ge $max_attempts ]; then
            echo "Instance did not stop within expected time. Exiting..."
            exit 1
          fi
          
      - name: Starting instance
        if: ${{ steps.check_status.outputs.status == 'Pending' && steps.instance-status-check.outputs.UNHEALTHY != '1' && steps.ec2-state.outputs.STATE == 'running' }}
        run: |
          echo "Instance is Stopped. Starting instance..."                
          aws ec2 start-instances --region ${{ inputs.Region }} --instance-ids ${{ inputs.InstanceId }}
          sleep 45

      - name: Post verify instance health
        if: ${{ steps.ec2-state.outputs.STATE == 'running' }}
        run: |
          cmd_id=$(aws ssm send-command \
            --document-name "${{ steps.get-ssm-doc.outputs.DOC_NAME }}" \
            --instance-ids ${{ inputs.InstanceId }} \
            --region ${{ inputs.Region }} \
            --parameters AlertName="keepalive" \
            --query 'Command.CommandId' --output text)
          
          echo "SSM Command ID: $cmd_id"
          echo "SSM Run Command Link- https://${{ inputs.REGION }}.console.aws.amazon.com/systems-manager/run-command/$cmd_id?region=${{ inputs.REGION }}"
          sleep 15  
          OUTPUT=$(aws ssm get-command-invocation \
            --command-id $cmd_id \
            --instance-id ${{ inputs.InstanceId }} \
            --output json)
          STATUS=$(echo "$OUTPUT" | jq -r '.Status')
          echo "SSM Command Status: $STATUS"
          if [[ "$STATUS" == "Pending" ]]; then
            echo "❌ SSM command stuck in $STATUS state for too long. Assuming instance is still responding slow."
            exit 1
          else
            echo "Instance is up & running."

  notify-on-failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: execute-keepalive-remediation
    steps:
      - name: Send Slack notification on failure
        run: |
          set -euxo pipefail
          curl -X POST -H "Authorization: Bearer xoxb-2601822751-6777186400710-fBZBEN2Ma97f93dkdcjswlaN" -H "Content-Type: application/json" --data '{"text":":x: *Keepalive Remediation Workflow Failed*","attachments":[{"color":"danger","title":"GitHub Workflow Failed","title_link":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}","text":"Check the workflow run for more details.","footer":"GitHub Actions","ts":"'$(date +%s)'"}]}' https://slack.com/api/chat.postMessage
