
name: remediation/Remediation-Keepalive

run-name: remediation/Remediation-Keepalive-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      Event:
        type: string
        description: Event
        required: true


jobs:
  remediation-keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra-Actions repo
        uses: actions/checkout@v3

      - name: Parse and print JSON input
        run: |
          echo "Received JSON input:"
          echo "${{ inputs.Event }}"
  
          # Parse JSON and print each value (example)
          echo "Parsing JSON:"
          echo "${{ inputs.Event }}" | jq .
